cic:
  enabled: False
  
  image: quay.io/citrix/citrix-k8s-ingress-controller:1.8.19
  pullPolicy: IfNotPresent
  openshift: false
  loginFileName:
  nsIP: x.x.x.x
  nsVIP:
  license:
    accept: no
  nsPort: 443
  nsProtocol: HTTPS
  logLevel: DEBUG
  nsNamespace:
  kubernetesURL:
  ipam: False
  logProxy:
  http2ServerSide: OFF
  ingressClass:
  defaultSSLCert:
  nodeWatch: false

  crds:
    install: true
    retainOnDelete: false

  exporter:
    required: false
    image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.3
    pullPolicy: IfNotPresent
    ports:
      containerPort: 8888

cpx:
  enabled: False

  image: quay.io/citrix/citrix-k8s-cpx-ingress:13.0-52.24
  pullPolicy: IfNotPresent
  cic:
    image: quay.io/citrix/citrix-k8s-ingress-controller:1.8.19
    pullPolicy: IfNotPresent
    required: true
  openshift: false
  lsIP:
  lsPort:
  nsNamespace:
  platform:
  logProxy:
  license:
    accept: no
  ingressClass:
  logLevel: DEBUG
  loginFileName: cpxlogin
  http2ServerSide: OFF
  defaultSSLCert:

  crds:
    install: true
    retainOnDelete: false

  exporter:
    required: false
    image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.3
    pullPolicy: IfNotPresent
    ports:
      containerPort: 8888

ci-ingress:
  enabled: False

  citrixCPX: false 

  metricExporter:
    required: true
    image: quay.io/citrix/citrix-adc-metrics-exporter
    version: 1.4.3
    port: 8888
    secure: "YES"
    logLevel: ERROR
    imagePullPolicy: IfNotPresent

  istioAdaptor:
    image: quay.io/citrix/citrix-istio-adaptor
    tag: 1.2.0
    imagePullPolicy: IfNotPresent
    netscalerUrl: null 
    proxyType: router
    secureConnect: true
    vserverIP:
    netProfile:
    ADMIP: 
    ADMFingerPrint:
    coeURL:
 
  istioPilot:
    name: istio-pilot
    namespace: istio-system
    secureGrpcPort: 15011
    insecureGrpcPort: 15010
    SAN: spiffe://cluster.local/ns/istio-system/sa/istio-pilot-service-account

  ingressGateway:
    image: quay.io/citrix/citrix-k8s-cpx-ingress
    tag: 13.0-47.22
    imagePullPolicy: IfNotPresent
    EULA: NO
    mgmtHttpPort: 10080
    mgmtHttpsPort: 10443
    httpNodePort: 30180
    httpsNodePort: 31443
    lightWeightCPX: 1 
    secretVolumes:
    #licenseServerIP: this value will be taken from istioAdaptor.ADMIP
    licenseServerPort: 27000 
    label: citrix-ingressgateway
    tcpPort:

ci-sidecar:
  enabled: False

  istioAdaptor:
    image: quay.io/citrix/citrix-istio-adaptor 
    tag: 1.2.0
    imagePullPolicy: IfNotPresent
    netscalerUrl: "http://127.0.0.1"
    proxyType: sidecar
    secureConnect: true
    ADMIP: 
    ADMFingerPrint: 
    coeURL:
 
  istioPilot:
    name: istio-pilot
    namespace: istio-system
    secureGrpcPort: 15011
    insecureGrpcPort: 15010
    SAN: "spiffe://cluster.local/ns/istio-system/sa/istio-pilot-service-account"

  cpxProxy:
    image: quay.io/citrix/citrix-k8s-cpx-ingress 
    tag: 13.0-47.22
    imagePullPolicy: IfNotPresent
    EULA: NO
    cpxSidecarMode: YES
    mgmtHttpPort: 10080
    mgmtHttpsPort: 10443
    #licenseServerIP: this value is taken from istio.Adaptor.ADMIP
    licenseServerPort: 27000

  sidecarWebHook:
    webhookImage: gcr.io/istio-release/sidecar_injector
    webhookImageVersion: 1.0.0
    imagePullPolicy: IfNotPresent

  webhook:
    injectionLabelName: cpx-injection

cnc:
  enabled: False
  image: quay.io/citrix/citrix-k8s-node-controller
  tag: 2.0.0
  pullPolicy: IfNotPresent
  license:
    accept: no
  nsIP:
  loginFileName:
  network:
  vtepIP:
  vxlan:
    id:
    port: 

  serviceAccount:
    create: true
