apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "citrix-k8s-node-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "citrix-k8s-node-controller.labels" . | nindent 4}}
spec:
  selector:
    matchLabels:
      {{- include "citrix-k8s-node-controller.selectorLabels" . | nindent 6}}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "citrix-k8s-node-controller.selectorLabels" . | nindent 8}}
    spec:
      serviceAccountName: {{ include "citrix-k8s-node-controller.serviceAccountName" . }}
      containers:
      - name: {{ include "citrix-k8s-node-controller.name" . }}
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        env:
        - name: EULA
          value: {{ required "Please set license.accept=yes for accepting Citrix License" .Values.license.accept | quote }}
        - name: NS_IP
          value: {{ required "Provide ADC VPX/MPX IP" .Values.nsIP | quote }}
        - name: NS_USER
          valueFrom:
            secretKeyRef:
              name: {{ required "Please provide secret for Citrix ADC credential" .Values.adcCredentialSecret }}
              key: username
        - name: NS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ required "Please provide secret for Citrix ADC credential" .Values.adcCredentialSecret }}
              key: password
        - name: NETWORK
          value: {{ required "Please provide network for VTEP overlay" .Values.network | quote }}
        - name: REMOTE_VTEPIP
          value: {{ required "Please provide ADC VPX/MPX SNIP" .Values.vtepIP | quote }}
        - name: VNID
          value: {{ required "Pleave provide VXLAN ID" .Values.vxlan.id | quote }}
        - name: VXLAN_PORT
          value: {{ required "Provide provide VXLAN port" .Values.vxlan.port | quote }}
        - name: CNI_TYPE
          value: {{ required "Provide CNI Type in cluster" .Values.cniType | quote }}
{{- if .Values.dsrIPRange }}
        - name: "DSR_IP_RANGE"
          value: {{ .Values.dsrIPRange | quote }}
{{- end }}
