# Default values for citrix-k8s-cpx-ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# cpximage contains information needed to fetch CPX image
cpx:
  image: quay.io/citrix/citrix-k8s-cpx-ingress:13.0-47.103
  pullPolicy: Always
# cicimage contains information needed to fetch CIC image
cic:
  image: quay.io/citrix/citrix-k8s-ingress-controller:1.7.6
  pullPolicy: Always
  required: true
# openshift is set to true if charts are being deployed in OpenShift environment.
openshift: false
# lsIP contains the Citrix Application Delivery Management (ADM) IP address to license Citrix ADC CPX.
lsIP:
# Specify the Citrix ADM port in lsPort only if you have changed it.
lsPort:
# nsNamespace is the prefix for the resources on the Citrix ADC
nsNamespace:
# Specify the platform license here.
platform:
# license is used accept the terms of the Citrix license
license:
  accept: no
# ingressClass is the  name of the Ingress Class
ingressClass:
# logLevel is to set level of CIC Logs
logLevel: DEBUG
# Default SSL certificate
defaultSSLCert:
# Elasticsearch or Kafka or Zipkin endpoint for Citrix observability exporter
logProxy:
# Set to ON to enables HTTP2 for Citrix ADC service group configurations
http2ServerSide: OFF
# exporter conatins information of prometheus-exporter
exporter:
  required: false
  image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.1
  pullPolicy: Always
  ports:
    containerPort: 8888
