# Default values for Citrix Cloud Native Deployments.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cic: 
  enabled: False

cpx:
  enabled: False

mcIngress:
  enabled: False

cnc:
  enabled: False

coe:
  enabled: False

ipam:
  enabled: False

iaIngress:
  enabled: False

iaSidecar:
  enabled: False

iaEgress:
  enabled: False

ao:
  enabled: False
