apiVersion: v2
appVersion: "1.13.15"
description: A Helm chart for Citrix ADC CPX with Citrix ingress Controller running as sidecar.
name: citrix-cpx-with-ingress-controller
version: 1.13.15
icon: https://raw.githubusercontent.com/citrix/citrix-helm-charts/gh-pages/icon.png
home: https://www.citrix.com
sources:
- https://github.com/citrix/citrix-k8s-ingress-controller
maintainers:
- name: priyankash-citrix
  email: priyanka.sharma@citrix.com
- name: subashd
  email: subash.dangol@citrix.com
