apiVersion: v1
kind: ConfigMap
metadata:
  name: cic-configmap
  labels:
    app: citrix-ingress-controller
data:
  LOGLEVEL: {{ .Values.logLevel | quote }}
  NS_PROTOCOL: "HTTP"
  NS_PORT: "80"
  NS_HTTP2_SERVER_SIDE: {{ .Values.http2ServerSide | quote }}
