# Default values for egress-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
citrixCPX: false

coe:
    coeURL:
    coeTracing: false

metricExporter:
    required: true
    image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.9
    port: 8888
    secure: "FALSE"
    logLevel: ERROR
    imagePullPolicy: IfNotPresent

istioPilot:
    name: istiod
    namespace: istio-system
    secureGrpcPort: 15012
    insecureGrpcPort: 15010
    SAN:


xDSAdaptor:
    image: quay.io/citrix/citrix-xds-adaptor:0.10.3
    imagePullPolicy: IfNotPresent
    proxyType: router
    secureConnect: true
    logLevel: DEBUG
    jsonLog: false
    defaultSSLListenerOn443: true


certProvider:
    caAddr: istiod.istio-system.svc
    caPort: 15012
    trustDomain: cluster.local
    certTTLinHours: 720
    clusterId: Kubernetes
    jwtPolicy: #specify third-party-jwt if Kubernetes cluster supports third-party tokens


egressGateway:
    netscalerUrl: null
    image: quay.io/citrix/citrix-k8s-cpx-ingress:13.1-30.52
    imagePullPolicy: IfNotPresent
    EULA: false
    mgmtHttpPort: 10080
    mgmtHttpsPort: 10443
    lightWeightCPX: "1"    
    label: citrix-egressgateway
    vserverIP: nsip
    adcServerName:
    netProfile:
    cpxLicenseAggregator:

ADMSettings:
    ADMIP:
    licenseServerIP:
    licenseServerPort: 27000
    bandWidthLicense: false
    bandWidth: 1000
    vCPULicense: false
    cpxCores:
    analyticsServerPort: 5557
    licenseEdition: PLATINUM

secretName: nsloginegress
