apiVersion: apps/v1
{{- if .Values.cpxBgpRouter }}
kind: DaemonSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: {{ include "citrix-cpx-ingress-controller.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "citrix-cpx-ingress-controller.fullname" . }}
{{- if not .Values.cpxBgpRouter }}
  replicas: 1
{{- end }}
  template:
    metadata:
      name: {{ include "citrix-cpx-ingress-controller.fullname" . }}
      labels:
        app: {{ include "citrix-cpx-ingress-controller.fullname" . }}
      annotations:
    spec:
      serviceAccountName: {{ include "citrix-cpx-ingress-controller.serviceAccountName" . }}
      containers:
        - name: cpx-ingress
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          securityContext:
             privileged: true
          env:
          - name: "EULA"
            value: "{{ .Values.license.accept }}"
          - name: "KUBERNETES_TASK_ID"
            value: ""
{{- if and .Values.openshift .Values.routeLabels }}
          - name: "ROUTE_LABELS"
            value: {{ .Values.routeLabels | quote}}
{{- end }}
{{- if and .Values.openshift .Values.namespaceLabels }}
          - name: "NAMESPACE_LABELS"
            value: {{ .Values.namespaceLabels | quote }}
{{- end }}
{{- if .Values.ADMSettings.licenseServerIP }}
          - name: "LS_IP"
            value: {{ .Values.ADMSettings.licenseServerIP | quote }}
{{- end }}
{{- if .Values.ADMSettings.licenseServerPort }}
          - name: "LS_PORT"
            value: {{ .Values.ADMSettings.licenseServerPort | quote }}
{{- end }}
{{- if not .Values.cpxBgpRouter }}
          - name: "MGMT_HTTP_PORT"
            value: {{ .Values.mgmtHttpPort | quote }}
          - name: "MGMT_HTTPS_PORT"
            value: {{ .Values.mgmtHttpsPort | quote }}
{{- end }}
{{- if .Values.cpxBgpRouter }}
          - name: NS_NETMODE
            value: HOST
{{- if .Values.nsIP }}
          - name: "NS_IP"
            value: "{{ .Values.nsIP }}"
{{- end }}
{{- if .Values.nsGateway }}
          - name: "NS_GATEWAY"
            value: "{{ .Values.nsGateway }}"
{{- end }}
{{- end }}
{{- if .Values.ADMSettings.ADMIP }}
          - name: "NS_MGMT_SERVER"
            value: {{ .Values.ADMSettings.ADMIP | quote }}
          - name: "NS_MGMT_FINGER_PRINT"
            value: {{ .Values.ADMSettings.ADMFingerPrint | quote }}
          - name: "NS_HTTP_PORT"
            value: {{ .Values.mgmtHttpPort | quote }}
          - name: "NS_HTTPS_PORT"
            value: {{ .Values.mgmtHttpsPort | quote }}
          - name: "LOGSTREAM_COLLECTOR_IP"
            value: {{ .Values.ADMSettings.ADMIP | quote }}
{{- end }}
#To povision bandwidth based licensing to Citrix ADC CPX from ADM, needs bandwidth
{{- if and ( .Values.ADMSettings.licenseServerIP ) (eq .Values.ADMSettings.bandWidthLicense true) }}
          - name: "BANDWIDTH"
            value: {{ required "Mention bandwidth for bandwidth based licensing" .Values.ADMSettings.bandWidth | quote }}
{{- end }}
#for multiple-PE support, need to set CPX_CORES
{{- if .Values.ADMSettings.licenseServerIP }}
{{- if or (eq .Values.ADMSettings.vCPULicense true) (eq .Values.ADMSettings.bandWidthLicense true) }}
          - name: "CPX_CORES"
            value: {{ .Values.ADMSettings.cpxCores | default 1 | quote }}
{{- end }}
{{- end }}
{{- if or (.Values.ADMSettings.ADMIP) (.Values.ADMSettings.licenseServerIP) }}
          - name: NS_MGMT_USER
            valueFrom:
              secretKeyRef:
                name: {{ required "Provide Secret for ADM/LicenseServer credentials" .Values.ADMSettings.loginSecret }}
                key: username
          - name: NS_MGMT_PASS
            valueFrom:
              secretKeyRef:
                name: {{ required "Provide Secret for ADM/LicenseServer credentials" .Values.ADMSettings.loginSecret }}
                key: password
{{- end }}
          volumeMounts:
            - mountPath: /var/deviceinfo
              name: shared-data
            - mountPath: /cpx/conf/
              name: cpx-volume1
            - mountPath: /cpx/crash/
              name: cpx-volume2
{{- if .Values.cic.required }}
        # Add cic as a sidecar
        - name: cic
          image: "{{ .Values.cic.image }}"
          imagePullPolicy: {{ .Values.cic.pullPolicy }}
          env:
          - name: "EULA"
            value: "{{ .Values.license.accept }}"
{{- if .Values.cpxBgpRouter }}
          - name: "NS_IP"
            value: {{ .Values.nsIP | default  "192.168.1.2" | quote }}
{{- else }}
          - name: "NS_IP"
            value: "127.0.0.1"
{{- end }}
          - name: "NS_APPS_NAME_PREFIX"
            value: {{ .Values.entityPrefix | default "k8s"}}
          - name: "NS_DEPLOYMENT_MODE"
            value: "SIDECAR"
{{- if .Values.cpxBgpRouter }}
{{- if eq (upper .Values.nsProtocol) "HTTPS" }}
          - name: NS_PROTOCOL
            value: HTTPS
          - name: NS_PORT
            value: "9443"
{{- else }}
          - name: NS_PROTOCOL
            value: HTTP
          - name: NS_PORT
            value: "9080"
{{- end }}
{{- if .Values.bgpPort }}
          - name: "BGP_PORT"
            value: {{ .Values.bgpPort | quote }}
{{- end }}
{{- end }}
          - name: "NS_ENABLE_MONITORING"
            value: "YES"
{{- if .Values.logProxy }}
          - name: "NS_LOGPROXY"
            value: {{ .Values.logProxy | quote }}
{{- end }}
{{- if .Values.ingressIP }}
          - name: "NS_VIP"
            value: {{ .Values.ingressIP | quote }}
{{- end }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
{{- if .Values.kubernetesURL }}
          - name: "kubernetes_url"
            value: "{{ .Values.kubernetesURL }}"
{{- end }}
{{- if .Values.cpxBgpRouter }}
          securityContext:
            runAsUser: 0
            capabilities:
              add:
              - NET_ADMIN
{{- end }}
          args:
            - --configmap
              {{ .Release.Namespace }}/cpx-{{ .Release.Name }}-configmap
{{- if .Values.ipam }}
            - --ipam
              citrix-ipam-controller
{{- end }}
{{- if .Values.cpxBgpRouter }}
            - --deployment-type
              kube-bgp-router
{{- end }}
{{- if .Values.ingressClass }}
            - --ingress-class
{{- range .Values.ingressClass}}
              {{.}}
{{- end }}
{{- end }}
{{- if .Values.defaultSSLCertSecret }}
            - --default-ssl-certificate
              {{ .Release.Namespace }}/{{ .Values.defaultSSLCertSecret }}
{{- end }}
{{- end }}
          volumeMounts:
            - mountPath: /var/deviceinfo
              name: shared-data
{{- if .Values.exporter.required }}
        - name: exporter
          image: "{{ .Values.exporter.image }}"
          imagePullPolicy: {{ .Values.exporter.pullPolicy }}
          args:
            - "--secure=no"
{{- if .Values.cpxBgpRouter }}
            - --target-nsip={{ .Values.nsIP | default "192.168.1.2" }}:9080
{{- else }}
            - "--target-nsip=127.0.0.1"
{{- end }}
            - "--port={{ .Values.exporter.ports.containerPort }}"
          env:
          - name: "NS_DEPLOYMENT_MODE"
            value: "SIDECAR"
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /var/deviceinfo
              name: shared-data
{{- end }}
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: cpx-volume1
          emptyDir: {}
        - name: cpx-volume2
          emptyDir: {}
{{- if and .Values.nodeSelector.key .Values.nodeSelector.value }}
      nodeSelector:
        {{ .Values.nodeSelector.key }}: {{ .Values.nodeSelector.value }}
{{- end }}

---
{{- if .Values.cpxBgpRouter }}
{{- if .Values.exporter.required }}
apiVersion: v1
kind: Service
metadata:
   name: exporter
   labels:
     app: exporter
     service-type: citrix-adc-cpx-monitor
spec:
   type: ClusterIP
   ports:
   - port: {{ .Values.exporter.ports.containerPort }}
     targetPort: {{ .Values.exporter.ports.containerPort }}
     name: exporter-port
   selector:
     app: {{ include "citrix-cpx-ingress-controller.fullname" . }}
{{- end }}
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: cpx-{{ .Release.Name }}-service
  labels:
    app: cpx-service
    service-type: citrix-adc-cpx-monitor
  annotations:
{{- if .Values.aws }}
{{- if or .Values.sslCertManagedByAWS .Values.serviceAnnotations.aws.sslCert }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ required "Please provide details of SSL Cert" .Values.serviceAnnotations.aws.sslCert | quote }}
{{- end }}
{{- if or .Values.sslCertManagedByAWS .Values.serviceAnnotations.aws.backendProtocol }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: {{ .Values.serviceAnnotations.aws.backendProtocol | default "http" | quote }}
{{- end }}
{{- if or .Values.sslCertManagedByAWS .Values.serviceAnnotations.aws.sslPorts }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: {{ .Values.serviceAnnotations.aws.sslPorts | default "https" | quote }}
{{- end }}
{{- if .Values.serviceAnnotations.aws.negotiationPolicy }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: {{ .Values.serviceAnnotations.aws.negotiationPolicy | quote }}
{{- end }}
{{- if or .Values.sslCertManagedByAWS .Values.serviceAnnotations.aws.proxyProtocol }}
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
{{- end }}
{{- if .Values.serviceAnnotations.aws.resourcesTags }}
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: {{ .Values.serviceAnnotations.aws.resourcesTags | quote }}
{{- end }}
{{- end }}
spec:
{{- if or ( and .Values.aws .Values.sslCertManagedByAWS) .Values.serviceType.loadBalancer.enabled }}
  externalTrafficPolicy: {{ .Values.serviceType.loadBalancer.externalTrafficPolicy }}
  type: LoadBalancer
{{- else if .Values.serviceType.nodePort.enabled }}
  type: NodePort
{{- end }}
  ports:
{{- if and .Values.aws .Values.sslCertManagedByAWS }}
  - port: 443
    protocol: TCP
    name: https
    targetPort: 80
{{- else }}
  - port: 80
    protocol: TCP
    name: http
{{- if and .Values.serviceType.nodePort.enabled .Values.serviceType.nodePort.httpPort }}
    nodePort: {{ .Values.serviceType.nodePort.httpPort }}
{{- end }}
  - port: 443
    protocol: TCP
    name: https
{{- if and .Values.serviceType.nodePort.enabled .Values.serviceType.nodePort.httpsPort }}
    nodePort: {{ .Values.serviceType.nodePort.httpsPort}}
{{- end }}
{{- end }}
{{- if .Values.exporter.required }}
  - port: {{ .Values.exporter.ports.containerPort }}
    targetPort: {{ .Values.exporter.ports.containerPort }}
    name: exporter-port
{{- end }}
  selector:
    app: {{ include "citrix-cpx-ingress-controller.fullname" . }}
{{- end }}

---

{{- if .Values.exporter.required }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
 name: citrix-adc-cpx-servicemonitor
 labels:
   servicemonitor: citrix-adc-cpx
spec:
 endpoints:
 - interval: 30s
   port: exporter-port
 selector:
   matchLabels:
     service-type: citrix-adc-cpx-monitor
 namespaceSelector:
   matchNames:
   - monitoring
   - default
   - {{ .Release.Namespace }}

{{- end }}
